# Generated by Django 3.1.5 on 2021-01-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0009_auto_20210124_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='food_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
